# Describing the Fruit API
openapi: "3.0.0"
info:
  title: Fruit API
  version: 1.0.0
paths:
  /fruits:
    get:
      tags:
        - Fruits
      description: API for returning a list of fruit documents
      summary: returns a list of fruit documents
      responses:
        '200':
          description: Fruit documents
        '500':
          description: Server Exception
        '501':
          description: MongoDB Exception
    post:
      tags:
        - Fruits
      description: API for adding a new fruit document
      summary: Creates a fruit document
      requestBody:
        description: Fruit information
        content:
          application/json:
            schema:
              required:
                - type
              properties:
                type:
                  type: string
      responses:
        '200':
          description: Fruit added
        '500':
          description: Server Exception
        '501':
          description: MongoDB Exception
  /fruits/{id}:
    get:
      tags:
        - Fruits
      description: API for returning a fruit document
      summary: returns a fruit document
      parameters:
        - name: id
          in: path
          required: true
          description: Fruit document Id
          schema:
            type: string
      responses:
        '200':
          description: Fruit document in JSON format
        '500':
          description: Server Exception
        '501':
          description: MongoDB Exception
